# Generated by Django 4.2.16 on 2026-03-25 09:07

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalNotificationSchema",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("revision", models.IntegerField(default=0)),
                ("name", models.TextField(blank=True)),
                ("schema", models.JSONField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical notification schema",
                "verbose_name_plural": "historical notification schemas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="IdMappingAll",
            fields=[
                (
                    "palvelukartta_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("palvelukartta_name_fi", models.TextField(blank=True, null=True)),
                ("tpr_internal_id", models.IntegerField(blank=True, null=True)),
                ("kaupunkialusta_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdMappingKaupunkialustaMaster",
            fields=[
                (
                    "palvelukartta_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("palvelukartta_name_fi", models.TextField(blank=True, null=True)),
                ("tpr_internal_id", models.IntegerField(blank=True, null=True)),
                ("kaupunkialusta_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatkoWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSchema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.IntegerField(default=0)),
                ("name", models.TextField(blank=True)),
                ("schema", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OntologyWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
