# Generated by Django 4.2.16 on 2026-03-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("Label", "Label"), ("Certificate", "Certificate")],
                        db_index=True,
                        default="Certificate",
                        max_length=16,
                    ),
                ),
                ("name_fi", models.CharField(max_length=125)),
                ("name_sv", models.CharField(max_length=125)),
                ("name_en", models.CharField(max_length=125)),
                ("url_fi", models.URLField(blank=True)),
                ("url_sv", models.URLField(blank=True)),
                ("url_en", models.URLField(blank=True)),
                ("displayed_in_myhelsinki", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name_fi"],
            },
        ),
        migrations.CreateModel(
            name="CustomerCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.IntegerField(db_index=True)),
                (
                    "custom_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_certificates",
                        to="base.certificate",
                    ),
                ),
            ],
            options={
                "unique_together": {("notification_id", "certificate")},
            },
        ),
    ]
