version: "3"
services: 

    # tpr-ilmoituslomake
    tpr-ilmoituslomake-admin:
        hostname: tpr-ilmoituslomake-admin
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "./run_web.sh"
        restart: always
        depends_on:
            - tpr-ilmoituslomake-db
        env_file:
            - ./local_dev/.env
        ports:
            - 8008:8008
        volumes:
            - ./ilmoituslomake:/app
            - ./local_dev/run_web.sh:/app/run_web.sh
        networks:
            - default