version: "3"
services: 
    tpr-ilmoituslomake-db:
        hostname: tpr-ilmoituslomake-db
        build:
            context: ./local_dev
            dockerfile: Dockerfile.database
        restart: always
        environment: 
            - POSTGRES_PASSWORD=plop123
            - PGDATA=/pgdata
        ports:
            - 5432:5432
        volumes:
            - ./pgdata:/pgdata
        networks:
            - default

    # tpr-ilmoituslomake
    tpr-ilmoituslomake:
        hostname: tpr-ilmoituslomake
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "./run_web.sh"
        restart: always
        depends_on:
            - tpr-ilmoituslomake-db
        env_file:
            - ./local_dev/.env
        ports:
            - 8008:8008
        volumes:
            - ./ilmoituslomake:/app
            - ./local_dev/run_web.sh:/app/run_web.sh
        networks:
            - default

    # tpr-reverse-proxy
    tpr-reverse-proxy:
        hostname: tpr-reverse-proxy
        build:
            context: ./nginx
            dockerfile: Dockerfile.nginx
        restart: always
        depends_on:
            - tpr-ilmoituslomake
            - tpr-ilmoituslomake-db
        ports:
            - 80:80
        networks:
            - default