# Generated by Django 4.2.16 on 2026-03-25 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import notification_form.models
import notification_form.storage
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalNotification",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("schema", models.IntegerField(default=1)),
                ("revision", models.IntegerField(db_index=True, default=0)),
                ("hauki_id", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("modified", "modified"),
                            ("rejected", "rejected"),
                            ("approved", "approved"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("data", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("moderated_notification_id", models.IntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical notification",
                "verbose_name_plural": "historical notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNotificationImage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, null=True)),
                ("filename", models.TextField(blank=True)),
                ("metadata", models.JSONField()),
                ("published", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("data", models.TextField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical notification image",
                "verbose_name_plural": "historical notification images",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema", models.IntegerField(default=1)),
                ("revision", models.IntegerField(db_index=True, default=0)),
                ("hauki_id", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("modified", "modified"),
                            ("rejected", "rejected"),
                            ("approved", "approved"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("moderated_notification_id", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, null=True)),
                ("filename", models.TextField(blank=True)),
                ("metadata", models.JSONField()),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    models.ImageField(
                        storage=notification_form.storage.PrivateAzureStorage(),
                        upload_to=notification_form.models.upload_image_to,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="images",
                        to="notification_form.notification",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
