# Generated by Django 4.2.16 on 2026-03-25 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import moderation.models
import moderation.storage
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalModeratedNotification",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("schema", models.IntegerField(default=1)),
                ("revision", models.IntegerField(db_index=True, default=0)),
                ("hauki_id", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("modified", "modified"),
                            ("rejected", "rejected"),
                            ("approved", "approved"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("data", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("notification_id", models.IntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical moderated notification",
                "verbose_name_plural": "historical moderated notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalModeratedNotificationImage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, null=True)),
                ("filename", models.TextField(blank=True)),
                ("metadata", models.JSONField()),
                ("published", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("data", models.TextField(max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical moderated notification image",
                "verbose_name_plural": "historical moderated notification images",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalModerationItem",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("notification_target_revision", models.IntegerField(default=0)),
                ("target_revision", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("change_request", "change_request"),
                            ("moderator_edit", "moderator_edit"),
                            ("moderation_task", "moderation_task"),
                        ],
                        db_index=True,
                        default="change_request",
                        max_length=16,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("change", "change"),
                            ("add", "add"),
                            ("delete", "delete"),
                            ("created", "created"),
                            ("modified", "modified"),
                        ],
                        db_index=True,
                        default="change",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("in_progress", "in_progress"),
                            ("closed", "closed"),
                            ("rejected", "rejected"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("user_place_name", models.TextField(blank=True, default="")),
                ("user_comments", models.TextField(default="")),
                ("user_details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical moderation item",
                "verbose_name_plural": "historical moderation items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ModeratedNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema", models.IntegerField(default=1)),
                ("revision", models.IntegerField(db_index=True, default=0)),
                ("hauki_id", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("modified", "modified"),
                            ("rejected", "rejected"),
                            ("approved", "approved"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("notification_id", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModeratedNotificationImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, null=True)),
                ("filename", models.TextField(blank=True)),
                ("metadata", models.JSONField()),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "data",
                    models.ImageField(
                        storage=moderation.storage.PublicAzureStorage(),
                        upload_to=moderation.models.upload_image_to,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModerationItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_target_revision", models.IntegerField(default=0)),
                ("target_revision", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("change_request", "change_request"),
                            ("moderator_edit", "moderator_edit"),
                            ("moderation_task", "moderation_task"),
                        ],
                        db_index=True,
                        default="change_request",
                        max_length=16,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("change", "change"),
                            ("add", "add"),
                            ("delete", "delete"),
                            ("created", "created"),
                            ("modified", "modified"),
                        ],
                        db_index=True,
                        default="change",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("in_progress", "in_progress"),
                            ("closed", "closed"),
                            ("rejected", "rejected"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("user_place_name", models.TextField(blank=True, default="")),
                ("user_comments", models.TextField(default="")),
                ("user_details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
