"""
Django settings for ilmoituslomake project.

Generated by 'django-admin startproject' using Django 2.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import environ


env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    ENABLE_ADMIN=(bool, False),
    FORCE_SCRIPT_NAME=(str, ""),
    FULL_WEB_ADDRESS=(str, "http://localhost"),
    # defaults to use Tunnistamo
    TOKEN_AUTH_ACCEPTED_AUDIENCE=(list, None),
    TOKEN_AUTH_AUTHSERVER_URL=(list, ["https://tunnistamo.hel.fi"]),
    TOKEN_AUTH_REQUIRE_SCOPE_PREFIX=(bool, False),
    TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX=(list, None),
    TOKEN_AUTH_FIELD_FOR_CONSENTS=(list, ["https://api.hel.fi/auth"])
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

HAUKI_SECRET_KEY = env("HAUKI_SECRET_KEY")

API_TOKEN = env("API_TOKEN")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ENABLE_ADMIN=env("ENABLE_ADMIN")

# 2025-06-02 jpla added backend to ALLOWED_HOSTS to avoid problems with forms
#ALLOWED_HOSTS = ["localhost", "backend", "tpr-ilmoituslomake", "asiointi.hel.fi", "tpr.hel.fi"]
ALLOWED_HOSTS = ["localhost", "backend", "tpr-ilmoituslomake", "asiointi.hel.fi", "tpr.hel.fi"]
CSRF_TRUSTED_ORIGINS = ["https://localhost", "https://backend", "https://tpr-ilmoituslomake", "https://asiointi.hel.fi", "https://tpr.hel.fi"]

# Application definition

INSTALLED_APPS = [
    "helusers.apps.HelusersConfig",
    "helusers.apps.HelusersAdminConfig",
    "users",
    # DRF
    "rest_framework",
    "rest_framework_api_key",
    # Django
    # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # GIS
    "django.contrib.gis",
    # Third-party apps
    "django_filters",
    "simple_history",
    "storages",
    # Our apps
    "base",
    "moderation",
    "notification_form",
    "api",
    "social_django",
    "translation",
    "opening_times"
    # "huey.contrib.djhuey",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "request_logging.middleware.LoggingMiddleware",
    # History
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "ilmoituslomake.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ilmoituslomake.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("DB_ENV_DB"),
        "USER": env("DB_ENV_POSTGRES_USER"),
        "PASSWORD": env("DB_ENV_POSTGRES_PASSWORD"),
        "HOST": env("DB_PORT_5432_TCP_ADDR"),
        "PORT": env("DB_PORT_5432_TCP_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "fi-FI"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_ROOT = "/opt/tpr-ilmoituslomake-backend/static/"
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Authentication
SESSION_SERIALIZER = "django.contrib.sessions.serializers.PickleSerializer"

AUTHENTICATION_BACKENDS = [
    "helusers.tunnistamo_oidc.TunnistamoOIDCAuth",
    "django.contrib.auth.backends.ModelBackend",
]
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SOCIAL_AUTH_TUNNISTAMO_KEY = env("TUNNISTAMO_CLIENT_ID")
SOCIAL_AUTH_TUNNISTAMO_SECRET = env("TUNNISTAMO_CLIENT_SECRET")
SOCIAL_AUTH_TUNNISTAMO_OIDC_ENDPOINT = env("TUNNISTAMO_CLIENT_OIDC_ENDPOINT", default="https://api.hel.fi/sso")

SOCIAL_AUTH_TUNNISTAMO_AUTH_EXTRA_ARGUMENTS = {
    "ui_locales": "fi"
}  # query param = ui_locales=<language code>
# HELUSERS_PASSWORD_LOGIN_DISABLED = True

# Django REST Framework
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 10.4.2025 jlasanen
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'helusers.oidc.ApiTokenAuthentication',
            'rest_framework.authentication.SessionAuthentication',
        ),
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 50,
}

HUEY = {
    "huey_class": "huey.SqliteHuey",  # Huey implementation to use.
    "name": DATABASES["default"]["NAME"],  # Use db name for huey.
    "results": True,  # Store return values of tasks.
    "store_none": False,  # If a task returns None, do not save to results.
    "immediate": DEBUG,  # If DEBUG=True, run synchronously.
    "utc": True,  # Use UTC for all times internally.
    "blocking": True,  # Perform blocking pop rather than poll Redis.
    "connection": {"filename": "huey.sqlite3", "cache_mb": 64, "fsync": True},
    "consumer": {
        "workers": 1,
        "worker_type": "thread",
        "initial_delay": 0.1,  # Smallest polling interval, same as -d.
        "backoff": 1.15,  # Exponential backoff using this rate, -b.
        "max_delay": 10.0,  # Max possible polling interval, -m.
        "scheduler_interval": 1,  # Check schedule every second, -s.
        "periodic": True,  # Enable crontab feature.
        "check_worker_health": True,  # Enable worker health checks.
        "health_check_interval": 1,  # Check worker health every second.
    },
}

# relay.hel.fi service
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# Use the following in development to write emails to the console instead:
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Azure storage
AZURE_STORAGE = env("AZURE_STORAGE")
PRIVATE_AZURE_CONTAINER = env("PRIVATE_AZURE_CONTAINER")
PRIVATE_AZURE_CONNECTION_STRING = env("PRIVATE_AZURE_CONNECTION_STRING")
PRIVATE_AZURE_READ_KEY = env("PRIVATE_AZURE_READ_KEY")
PUBLIC_AZURE_CONTAINER = env("PUBLIC_AZURE_CONTAINER")
PUBLIC_AZURE_CONNECTION_STRING = env("PUBLIC_AZURE_CONNECTION_STRING")
# PUBLIC_AZURE_READ_KEY = env("PUBLIC_AZURE_READ_KEY")

# Setup support for proxy headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# FORCE_SCRIPT_NAME = "/TPRalusta_testi"
FORCE_SCRIPT_NAME = env("FORCE_SCRIPT_NAME")

FULL_WEB_ADDRESS = env("FULL_WEB_ADDRESS") + FORCE_SCRIPT_NAME

DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440 * 10

JWT_IMAGE_SECRET = env("JWT_IMAGE_SECRET")

API_KEY_CUSTOM_HEADER = "HTTP_OPEN_API_KEY"

HAUKI_API_URL = env("HAUKI_API_URL")
HAUKI_UI_URL = env("HAUKI_UI_URL")

ACCESSIBILITY_API_URL = env("ACCESSIBILITY_API_URL")
ACCESSIBILITY_APP_URL = env("ACCESSIBILITY_APP_URL")
KAUPUNKIALUSTA_URL = env("KAUPUNKIALUSTA_URL")
TPR_SYSTEM_ID = env("TPR_SYSTEM_ID")
TPR_CHECKSUM_SECRET = env("TPR_CHECKSUM_SECRET")
KAUPUNKIALUSTA_SYSTEM_ID = env("KAUPUNKIALUSTA_SYSTEM_ID")
KAUPUNKIALUSTA_CHECKSUM_SECRET = env("KAUPUNKIALUSTA_CHECKSUM_SECRET")

# configure social_django authentication pipeline to handle the users.
from helusers.defaults import SOCIAL_AUTH_PIPELINE

# enable back channel logout
HELUSERS_BACK_CHANNEL_LOGOUT_ENABLED = True

OIDC_API_TOKEN_AUTH = {
    "AUDIENCE": env("TOKEN_AUTH_ACCEPTED_AUDIENCE"),
    "ISSUER": env("TOKEN_AUTH_AUTHSERVER_URL"),
    "REQUIRE_API_SCOPE_FOR_AUTHENTICATION": env("TOKEN_AUTH_REQUIRE_SCOPE_PREFIX"),
    "API_AUTHORIZATION_FIELD": env("TOKEN_AUTH_FIELD_FOR_CONSENTS"),
    "API_SCOPE_PREFIX": env("TOKEN_AUTH_ACCEPTED_SCOPE_PREFIX"),
}


GDPR_API_MODEL = AUTH_USER_MODEL
GDPR_API_QUERY_SCOPE = "gdprquery"
GDPR_API_DELETE_SCOPE = "gdprdelete"
GDPR_API_URL_PATTERN = "v1/user/<uuid:uuid>"
GDPR_API_MODEL_LOOKUP = "uuid"
GDPR_API_USER_PROVIDER = "users.gdpr.get_user"
GDPR_API_DELETER = "users.gdpr.delete_gdpr_data"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

