# Base on offical NGINX Alpine image
FROM nginx:alpine

# Remove any existing config files
RUN rm /etc/nginx/conf.d/*

# Copy config files
# *.conf files in conf.d/ dir get included in main config
COPY ./default.conf /default.conf 
 

COPY ./proxy_host.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/proxy_host.sh

# Expose the listening port
EXPOSE 80

# Launch NGINX
CMD ["nginx", "-g", "daemon off;" ]