# Generated by Django 4.2.16 on 2026-03-25 09:07

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalTranslationTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("request_id", models.IntegerField()),
                ("target_revision", models.IntegerField(db_index=True, default=0)),
                ("language_from", models.TextField()),
                ("language_to", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("translation_task", "translation_task")],
                        db_index=True,
                        default="translation_task",
                        max_length=16,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("change", "change"),
                            ("add", "add"),
                            ("delete", "delete"),
                            ("created", "created"),
                            ("modified", "modified"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("in_progress", "in_progress"),
                            ("closed", "closed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical translation task",
                "verbose_name_plural": "historical translation tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TranslationData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_revision", models.IntegerField()),
                ("language", models.TextField()),
                ("name", models.TextField()),
                ("description_long", models.TextField()),
                ("description_short", models.TextField()),
                ("images", models.JSONField(default=dict)),
                ("website", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TranslationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("request_id", models.IntegerField()),
                ("target_revision", models.IntegerField(db_index=True, default=0)),
                ("language_from", models.TextField()),
                ("language_to", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("translation_task", "translation_task")],
                        db_index=True,
                        default="translation_task",
                        max_length=16,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("change", "change"),
                            ("add", "add"),
                            ("delete", "delete"),
                            ("created", "created"),
                            ("modified", "modified"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("in_progress", "in_progress"),
                            ("closed", "closed"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
