# Generated by Django 2.2.17 on 2021-08-11 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_auto_20210811_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.IntegerField()),
                ('category', models.CharField(choices=[('change_request', 'change_request'), ('translation_edit', 'translation_edit'), ('translation_task', 'translation_task')], db_index=True, default='change_request', max_length=16)),
                ('item_type', models.CharField(choices=[('change', 'change'), ('add', 'add'), ('delete', 'delete'), ('created', 'created'), ('modified', 'modified')], db_index=True, default='change', max_length=16)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('closed', 'closed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translation_moderator', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_items', to='moderation.ModeratedNotification')),
                ('translator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translation_translator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTranslationTask',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('requestId', models.IntegerField()),
                ('category', models.CharField(choices=[('change_request', 'change_request'), ('translation_edit', 'translation_edit'), ('translation_task', 'translation_task')], db_index=True, default='change_request', max_length=16)),
                ('item_type', models.CharField(choices=[('change', 'change'), ('add', 'add'), ('delete', 'delete'), ('created', 'created'), ('modified', 'modified')], db_index=True, default='change', max_length=16)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('closed', 'closed')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moderation.ModeratedNotification')),
                ('translator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical translation task',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
