# Generated by Django 4.2.16 on 2026-05-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_organization_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
